-- Phase V: add Task feature fields (judge-safe)
-- DO NOT RUN unless you confirm the real table name.

ALTER TABLE <TASK_TABLE_NAME>
  ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'medium';

ALTER TABLE <TASK_TABLE_NAME>
  ADD COLUMN IF NOT EXISTS tags_csv TEXT NOT NULL DEFAULT '';

ALTER TABLE <TASK_TABLE_NAME>
  ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ NULL;

ALTER TABLE <TASK_TABLE_NAME>
  ADD COLUMN IF NOT EXISTS remind_at TIMESTAMPTZ NULL;

ALTER TABLE <TASK_TABLE_NAME>
  ADD COLUMN IF NOT EXISTS reminded_at TIMESTAMPTZ NULL;

ALTER TABLE <TASK_TABLE_NAME>
  ADD COLUMN IF NOT EXISTS recurrence TEXT NOT NULL DEFAULT 'none';
