apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.worker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name }}
      {{- if and .Values.worker.dapr .Values.worker.dapr.enabled }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{ .Values.worker.dapr.appId }}"
        dapr.io/app-port: "{{ .Values.worker.dapr.appPort }}"
      {{- end }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.worker.containerPort }}
          {{- with .Values.worker.env }}
          env:
          {{- range $k, $v := . }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
          {{- end }}
          {{- end }}
