apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: nimbus
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      secretKeyRef:
        name: redpanda-kafka-secret
        key: brokers
    - name: authType
      value: "password"
    - name: saslUsername
      secretKeyRef:
        name: redpanda-kafka-secret
        key: saslUsername
    - name: saslPassword
      secretKeyRef:
        name: redpanda-kafka-secret
        key: saslPassword
    - name: saslMechanism
      value: "SCRAM-SHA-256"
    - name: securityProtocol
      value: "SASL_SSL"
    - name: consumerGroup
      value: "nimbus-phase5"

auth:
  secretStore: secretstore

scopes:
  - nimbus-backend
  - nimbus-worker
