apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-kafka
  namespace: nimbus
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: redpanda:9092
    - name: authRequired
      value: "true"
    - name: saslUsername
      secretKeyRef:
        name: kafka-secrets
        key: username
    - name: saslPassword
      secretKeyRef:
        name: kafka-secrets
        key: password
  auth:
    secretStore: secretstore
scopes:
  - nimbus-backend
  - nimbus-worker
